### PR TITLE
feat(frontend): Use Melt UI custom selects

### PR DESCRIPTION
**Pull request by bitbloxhub**
Use [Melt UI Select](https://www.melt-ui.com/docs/builders/select) for the selects.

### CODE REVIEW

**Review by billkamp — APPROVED** [review]
Looks fine.

**Comment by bitbloxhub** [comment]
> Looks fine.

@billkamp, have you locally tested the latest version of this?

**Review by billkamp — APPROVED** [review]
k

**Review by billkamp — APPROVED** [review]
Main works fine now.

**Pull request merged**
