### PR TITLE
Set up UnoCSS for styling.

### PR DESCRIPTION
**Pull request by bitbloxhub**
Use [UnoCSS](https://unocss.dev/) for styling with [unocss-catppuccin](https://github.com/catuhana/unocss-catppuccin).

Patches [css-tree](https://github.com/csstree/csstree?tab=readme-ov-file) because of https://github.com/oven-sh/bun/issues/13076.

Add [svelte-body](https://github.com/ghostdevv/svelte-body) and [svelte-persisted-store](https://github.com/joshnuss/svelte-persisted-store) for theming.

(Probably should be multiple commits, but to lazy to do that.)

### CODE REVIEW

**Review by billkamp — APPROVED** [review]
lota changes
ok

**Comment by bitbloxhub** [comment]
@billkamp did you test them locally?

**Comment by billkamp** [comment]
Nope. You have to show me how let me zoom today.

**Review by billkamp — APPROVED** [review]
I am not sure what this means.

**Pull request merged**
